packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@eslint/js": ^9.38.0
  convex: ^1.27.0
  "@types/node": ^20
  "@tailwindcss/postcss": ^4.1.16
  typescript: ^5
  dotenv: "^17.2.2"
  next: 16.1.1
  arktype: "^2.1.0"
  next-themes: "^0.4.6"
  tailwindcss: ^4.1.16
  effect: "^3.19.14"
  eslint: ^9.38.0
  prettier: ^3.6.2
  vitest: ^2.1.8

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
